---
# Original values sourced from:
# https://gist.githubusercontent.com/bouroo/bc52ad58a6e75d44e5235b229e9ca988/raw/8d299c486eb5689f045f25e3619cbc91ffc2de86/65-k8s.conf
# https://gist.githubusercontent.com/bouroo/bc52ad58a6e75d44e5235b229e9ca988/raw/8d299c486eb5689f045f25e3619cbc91ffc2de86/90-k8s.conf

- ansible.posix.sysctl:
    name: net.core.default_qdisc
    value: fq
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    state: present

- ansible.posix.sysctl:
    name: net.core.rmem_max
    value: 16777216
    state: present

- ansible.posix.sysctl:
    name: net.core.wmem_max
    value: 16777216
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 65536 16777216
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 65536 16777216
    state: present

- ansible.posix.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- ansible.posix.sysctl:
    name: fs.file-max
    value: 1048576
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.ip_local_port_range
    value: 1024 65535
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 8096
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.core.somaxconn
    value: 8192
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.vs.expire_nodest_conn
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.vs.expire_quiescent_template
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 30
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 600
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: 10
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 15
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 2
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 2
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_timestamps
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_sack
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_fack
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present

- ansible.posix.sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    state: present

- ansible.posix.sysctl:
    name: vm.swappiness
    value: 10
    state: present

- ansible.posix.sysctl:
    name: vm.dirty_background_ratio
    value: 5
    state: present

- ansible.posix.sysctl:
    name: vm.dirty_ratio
    value: 10
    state: present

- ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    state: present

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- ansible.posix.sysctl:
    name: fs.file-max
    value: 1048576
    state: present

- ansible.posix.sysctl:
    name: fs.aio-max-nr
    value: 1048576
    state: present

- ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: 512
    state: present

- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

